# -*- coding: utf-8 -*-
"""testing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GzlelST2ARmdEUbyAymj5zbthLCBPfON

# 1. Upload the 'test.csv' file at the 'upload' button
# 2. It will replace the blank row with 'hello'
# 3. Lastly it will spit out an 'output.csv'
"""

# !pip install pandas

from ipywidgets import FileUpload
from IPython.display import display
import pandas as pd
import io

upload = FileUpload(accept='.csv')
display(upload)

while True:
    try:
        uploaded_file = list(upload.value.values())[0]
        csv_text = io.StringIO(uploaded_file['content'].decode('utf-8'))

        # df = pd.read_csv('test.csv', skip_blank_lines=False)
        df = pd.read_csv(csv_text, skip_blank_lines=False)

        df.fillna('hello', inplace=True)

        # df.to_csv('output.csv', index=False)

        from IPython.display import Javascript
        js_download = """
        var csv = '%s';

        var filename = 'output.csv';
        var blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
        if (navigator.msSaveBlob) { // IE 10+
            navigator.msSaveBlob(blob, filename);
        } else {
            var link = document.createElement("a");
            if (link.download !== undefined) { // feature detection
                // Browsers that support HTML5 download attribute
                var url = URL.createObjectURL(blob);
                link.setAttribute("href", url);
                link.setAttribute("download", filename);
                link.style.visibility = 'hidden';
                document.body.appendChild(link);
                link.click();
                document.body.removeChild(link);
            }
        }
        """ % df.to_csv(index=False).replace('\n','\\n').replace("'","\'")

        Javascript(js_download)
    except:
        pass







